basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'

    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='product_creator')
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default='images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=4, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])

    def __str__(self):
        return self.title

class Review(models.Model):
    Product = models.ForeignKey(Product,on_delete=models.CASCADE)
    comment = models.TextField(max_length=1000)
    rating=models.FloatField(max_length=5)

    
    

store/forms.py
from django import forms
from .models import 

class ReviewForm (forms.ModelForm):
    class Meta:
        fields=("comment","rating")

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/index.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    products = Product.products.filter(category=category)
    return render(request, 'store/category.html', {'category': category, 'products': products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, in_stock=True)
    return render(request, 'store/single.html', {'product': product})

templates/store/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container" style="max-width: 1000px">
  <div class="col-12">
    <h1 class="h2">{{ category.name|title }}</h1>
  </div>
  <div class="col-12 d-flex justify-content-between">
   
  </div>
  <hr />
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">There are currently no products active <a href="{% url 'store:store_home' %}">Home</a></div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card border-0">
            <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
            <div class="card-body px-0">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">RS.{{product.price}}</small>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% block title %}Store - Low Prices in Books & more{% endblock %}
{% block content %}

<section class="py-0 text-center container">
  <div class="row py-lg-0">
    <div class="col-lg-6 col-md-8 mx-auto bg-white">
      <h1 class="h1 fw-bold">eBook Store</h1>
      <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator,
        etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
          </div>
  </div>
</section>
  <div class="container">
    <div class="row">
      <div class="album py-0">
        <div class="pb-3">
          <h1 class="h3">All Books</h1>
        </div>
        {% if not products %}
        <div class="col-12">There are currently no products active</div>
          {% else %}
          <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
          {% for product in products %}
          <div class="col">
            <div class="card border-0">
              <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
              <div class="card-body px-0">
                <p class="card-text">
                  <a class="text-dark text-decoration-none"
                    href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}...</a>
                </p>
                <div class="fw-bold">{{product.category}}</div>
                <div class="fw-bold">RS.{{product.price}}</div>
                
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>

  {% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% load static %} 
{% block stylesheet %}{% static 'store/css/store.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Product{% endif %}
{% endblock %}
{% block content %}

<div class="container">
  <div class="row g-3">
    <div class="col-md-5 ps-3 col-lg-5 order-md-last p-0 order-1">
      <div class="d-grid gap-2">
        <div class="d-flex d-flex-inline justify-content-between">
          <div><span class="h3">RS.{{ product.price }}</span>
            <p class="text-muted">includes tax</p>
          </div>
          <div>
            <label for="select">Qty</label>
            <select id="select" class="h6 store-select-dropdown">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </div>
        <hr>
        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">Add to
          basket</button>
         </div>
    </div>
    <div class="col-md-7 col-lg-7 p-0">
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="card-body p-1">
              <h1 class="mb-0 h2 pe-4 pb-4">{{ product.title }}</h1>
              <div class="fw-bold">{{product.author}}(author)</div>
              <div class="bg-light"><img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image"
                  src="{{ product.image.url }}"> </div>
                  <div class="fw-light">Description: {{product.description}}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();
    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },
      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>

{% endblock %}